# Generated by Django 4.0.3 on 2022-05-06 14:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=None, upload_to='profile_pics')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(default='Male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('sign', models.CharField(max_length=15)),
                ('value', models.IntegerField(primary_key=True, serialize=False)),
                ('html_code', models.CharField(default='', max_length=10)),
                ('unicode_value', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('from_ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ind', to='astro.individual')),
                ('to_ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ind', to='astro.individual')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='jupiter_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupiter_sign', to='astro.zodiac'),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_seen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to='astro.location'),
        ),
        migrations.AddField(
            model_name='individual',
            name='mars_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mars_sign', to='astro.zodiac'),
        ),
        migrations.AddField(
            model_name='individual',
            name='mercury_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercury_sign', to='astro.zodiac'),
        ),
        migrations.AddField(
            model_name='individual',
            name='moon_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moon_sign', to='astro.zodiac'),
        ),
        migrations.AddField(
            model_name='individual',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pob', to='astro.location'),
        ),
        migrations.AddField(
            model_name='individual',
            name='rising_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rising_sign', to='astro.zodiac'),
        ),
        migrations.AddField(
            model_name='individual',
            name='sun_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sun_sign', to='astro.zodiac'),
        ),
        migrations.AddField(
            model_name='individual',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='venus_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venus_sign', to='astro.zodiac'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('ind1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind1', to='astro.individual')),
                ('ind2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind2', to='astro.individual')),
            ],
        ),
    ]
